# Cost Configuration for Client Project Pricing
# Updated: 2025-10-30
#
# This file contains all subscription costs, API pricing, hardware depreciation,
# and operational expenses for calculating project costs.

# ==============================================================================
# MONTHLY SUBSCRIPTIONS
# ==============================================================================
subscriptions:
  ai_tools:
    claude_max:
      cost: 200.00
      currency: USD
      billing_cycle: monthly
      notes: "Anthropic Claude Max subscription for web + API usage"

    chatgpt_pro:
      cost: 20.00
      currency: USD
      billing_cycle: monthly
      notes: "OpenAI ChatGPT Pro subscription"

    cursor_ai_pro:
      cost: 20.00
      currency: USD
      billing_cycle: monthly
      notes: "Cursor AI IDE subscription"

    gemini_pro:
      cost: 20.00
      currency: USD
      billing_cycle: monthly
      notes: "Google Gemini Advanced subscription (2TB storage included)"

    grok:
      cost: 40.00
      currency: USD
      billing_cycle: monthly
      notes: "X.ai Grok premium access"

  development_platforms:
    vercel_pro:
      cost: 20.00
      currency: USD
      billing_cycle: monthly
      notes: "Vercel Pro with hobby Supabase projects"

    replit_core:
      cost: 25.00
      currency: USD
      billing_cycle: monthly
      notes: "Replit Core subscription"

    lovable_pro:
      cost: 25.00
      currency: USD
      billing_cycle: monthly
      notes: "Lovable AI website builder"

  data_scraping:
    bright_data:
      cost: 500.00
      currency: USD
      billing_cycle: monthly
      notes: "BrightData proxy/scraping service - estimate, varies by usage"
      usage_based: true

    apify:
      cost: 49.00
      currency: USD
      billing_cycle: monthly
      notes: "Apify scraping platform - starter plan, usage-based overage"
      usage_based: true

  cloud_infrastructure:
    google_cloud:
      cost: 50.00
      currency: USD
      billing_cycle: monthly
      notes: "Google Cloud Platform - estimate, varies by API usage"
      usage_based: true

# Total Monthly Subscriptions: ~$989/month (base) + usage overages

# ==============================================================================
# PAY-PER-USE API COSTS
# ==============================================================================
api_pricing:
  openai:
    whisper:
      cost_per_minute: 0.006
      unit: "minute"
      notes: "OpenAI Whisper API transcription"

    gpt4_vision:
      cost_per_1k_tokens: 0.01
      cost_per_image: 0.00765  # ~1k tokens per image at high detail
      unit: "tokens/images"
      notes: "GPT-4 Vision API for image analysis"

    gpt4_turbo:
      input_cost_per_1M_tokens: 10.00
      output_cost_per_1M_tokens: 30.00
      unit: "tokens"
      notes: "GPT-4 Turbo for text generation"

  anthropic:
    claude_sonnet:
      input_cost_per_1M_tokens: 3.00
      output_cost_per_1M_tokens: 15.00
      unit: "tokens"
      notes: "Claude 3.5 Sonnet API"

    claude_opus:
      input_cost_per_1M_tokens: 15.00
      output_cost_per_1M_tokens: 75.00
      unit: "tokens"
      notes: "Claude 3 Opus API"

  google_cloud:
    slides_api:
      cost_per_1k_requests: 0.00
      unit: "requests"
      notes: "Google Slides API - free tier up to quota"
      free_quota: 300
      quota_period: "per_minute"

    drive_api:
      cost_per_1k_requests: 0.00
      unit: "requests"
      notes: "Google Drive API - free tier up to quota"
      free_quota: 1000
      quota_period: "per_100_seconds"

  apify:
    tiktok_scraper:
      cost_per_1k_results: 5.00
      unit: "results"
      notes: "Free TikTok scraper actor - uses compute units from plan"
      included_in_subscription: true

  bright_data:
    web_unlocker:
      cost_per_1k_requests: 3.00
      unit: "requests"
      notes: "Web Unlocker API for complex sites"
      included_in_subscription: false

# ==============================================================================
# HARDWARE COSTS (Depreciation/Amortization)
# ==============================================================================
hardware:
  mac_studio:
    purchase_price: 3999.00
    purchase_date: "2023-06-01"
    depreciation_years: 4
    monthly_depreciation: 83.31
    notes: "Mac Studio M2 Ultra - primary workstation"

  macbook_pro_2024:
    purchase_price: 3499.00
    purchase_date: "2024-01-15"
    depreciation_years: 4
    monthly_depreciation: 72.90
    notes: "MacBook Pro 16\" M3 Max - mobile workstation"

  synology_nas:
    purchase_price: 1200.00
    purchase_date: "2022-08-01"
    depreciation_years: 5
    monthly_depreciation: 20.00
    notes: "Synology NAS for data storage and backup"

  samsung_s24_ultra:
    purchase_price: 1299.00
    purchase_date: "2024-02-01"
    depreciation_years: 3
    monthly_depreciation: 36.08
    notes: "Samsung Galaxy S24 Ultra - mobile device"

  hp_printer:
    purchase_price: 400.00
    purchase_date: "2021-03-01"
    depreciation_years: 5
    monthly_depreciation: 6.67
    notes: "HP LaserJet printer"
    fully_depreciated: true

# Total Monthly Hardware Depreciation: ~$219/month

# ==============================================================================
# OPERATIONAL COSTS
# ==============================================================================
operational:
  internet:
    att_fiber:
      cost: 110.00
      currency: USD
      billing_cycle: monthly
      notes: "AT&T fiber internet service"

  mobile:
    google_fi:
      cost: 70.00
      currency: USD
      billing_cycle: monthly
      notes: "Google Fi unlimited plan - single user estimate"

  electricity:
    estimated_compute:
      cost: 50.00
      currency: USD
      billing_cycle: monthly
      notes: "Estimated additional electricity for compute equipment"

# Total Monthly Operational: ~$230/month

# ==============================================================================
# LABOR RATES
# ==============================================================================
labor:
  consultant_hourly_rate: 150.00
  notes: "Your hourly consulting rate - adjust as needed"

  task_categories:
    discovery_research: 150.00
    data_collection: 125.00
    data_analysis: 150.00
    report_writing: 150.00
    presentation_design: 125.00
    client_meetings: 175.00
    project_management: 150.00

# ==============================================================================
# COST ALLOCATION METHODOLOGY
# ==============================================================================
allocation_methodology:
  subscriptions:
    method: "proportional_usage"
    description: |
      Subscriptions are allocated to projects based on:
      1. Duration: % of month spent on project
      2. Intensity: % of daily work time on project
      3. Tool Usage: Which tools were actively used

      Formula: (Monthly Cost / Billable Projects) * (Project Days / Total Days)

  hardware:
    method: "usage_time"
    description: |
      Hardware depreciation allocated based on active usage time.
      Formula: (Monthly Depreciation) * (Project Hours / Total Work Hours)

  operational:
    method: "overhead_rate"
    description: |
      Operational costs allocated as overhead percentage.
      Formula: (Total Operational / Total Work Hours) * Project Hours

  apis:
    method: "direct_attribution"
    description: |
      API costs directly attributed to project based on actual usage logs.
      Track via API provider dashboards and usage logs.

# ==============================================================================
# EXAMPLE CALCULATIONS
# ==============================================================================
example_project_costs:
  garage_organizers_report:
    project_duration_days: 45
    active_work_days: 30
    estimated_hours: 120

    estimated_costs:
      labor: 18000.00  # 120 hours * $150/hr
      subscriptions_allocated: 989.00  # Full month of subscriptions
      hardware_allocated: 219.00  # Full month of hardware depreciation
      operational_allocated: 230.00  # Full month operational
      api_costs:
        openai_whisper: 15.00  # ~42 videos * 60 sec * $0.006/min
        openai_vision: 50.00  # ~500 frames analyzed
        apify_tiktok: 30.00  # ~200 videos scraped
        anthropic_claude: 25.00  # Emotion analysis
      total_api: 120.00

    total_project_cost: 19558.00

    pricing_strategy:
      cost_basis: 19558.00
      markup_percentage: 50  # 50% markup
      quoted_price: 29337.00
      rounded_quote: 29500.00
