# API Pricing Configuration
# For calculating costs from Claude Code chat logs

api_pricing:
  anthropic:
    claude_sonnet:
      input_cost_per_1M_tokens: 3.00
      output_cost_per_1M_tokens: 15.00
      notes: "Claude 3.5 Sonnet - used by Claude Code"

  openai:
    whisper:
      cost_per_minute: 0.006
      notes: "Whisper API transcription"

    gpt4_vision:
      cost_per_image: 0.00765
      notes: "GPT-4 Vision API"

    gpt4_turbo:
      input_cost_per_1M_tokens: 10.00
      output_cost_per_1M_tokens: 30.00
      notes: "GPT-4 Turbo"

  google:
    gemini_pro:
      input_cost_per_1M_tokens: 0.00
      output_cost_per_1M_tokens: 0.00
      notes: "Free tier for now"

# Fixed costs per report
report_pricing:
  fixed_cost_per_report: 4100.00
  covers:
    - "2x monthly fixed costs ($1,438 × 2 = $2,876)"
    - "8 hours consulting time (8 × $150 = $1,200)"
    - "API costs additional"
