# 3M Brand Perceptions - Garage Organization
# AI-Generated Brand Selection via WebSearch + Claude Reasoning
# Generated: 2025-10-30
# Method: Research-driven analysis, not hardcoded assumptions

brands:
  - name: "Command"
    priority: 1
    garage_relevance: "HIGH"

    rationale: |
      Direct garage organization application with existing consumer awareness.
      CRITICAL GAP IDENTIFIED: Consumers love damage-free mounting philosophy BUT need
      heavy-duty capacity for garage use (bikes, tools, ladders require 50-100+ lb capacity).
      Current perception: "Convenience brand, not durability brand (yet)".
      Competitor dominance: Steel-mounted hooks dominate heavy garage storage.

      INNOVATION OPPORTUNITY: Heavy-duty damage-free hooks that bridge convenience + durability.

    consumer_perception_themes:
      - "Damage-free mounting (loved)"
      - "Weight limit concerns for heavy items (frustration)"
      - "Light-duty perception vs heavy-duty garage needs (gap)"

    strategic_questions:
      - "Can Command credibly extend to heavy-duty garage applications?"
      - "Would consumers believe Command could hold bikes and power tools?"
      - "What's the trade-off between damage-free and weight capacity?"

    search_terms:
      - "Command hooks garage organization"
      - "Command heavy duty garage"
      - "Command hooks weight limit complaints"
      - "damage-free garage storage hooks"

  - name: "Scotch-Brite"
    priority: 2
    garage_relevance: "HIGH"

    rationale: |
      Strong workshop authenticity - already used for engine parts, machine tools, and
      garage equipment cleaning. 3M markets "Garage Toolkit" product, confirming awareness
      of this market. Consumer perception: Professional/maker tool, beyond kitchen use.

      BRAND STRENGTH: High DIY authenticity and durability perception in workshop context.

    consumer_perception_themes:
      - "Workshop cleaning (engine parts, machine tools)"
      - "Professional/maker credibility (not just kitchen)"
      - "Existing Garage Toolkit product (3M knows this market)"

    strategic_questions:
      - "How can Scotch-Brite own the garage cleaning category?"
      - "What garage-specific cleaning jobs are underserved?"
      - "Does brand extend beyond cleaning to garage organization?"

    search_terms:
      - "Scotch-Brite garage cleaning"
      - "Scotch-Brite workshop tools"
      - "garage cleaning supplies reviews"
      - "Scotch-Brite heavy duty garage"

  - name: "Scotch"
    priority: 3
    garage_relevance: "HIGH"

    rationale: |
      DIY enabler brand across multiple garage applications. Not hero product, but essential
      supporting role: labeling, mounting, organizing. ScotchBlue painter's tape commonly
      used for clean paint lines on pegboards and garage DIY projects.

      INSIGHT: Tape storage itself is a garage organization challenge (multiple types scattered).

    consumer_perception_themes:
      - "DIY project enabler (not hero product)"
      - "Labeling and organization applications"
      - "ScotchBlue for garage DIY projects"
      - "Tape storage itself needs organization"

    strategic_questions:
      - "Can Scotch move from supporting role to hero in garage context?"
      - "Is there a garage-specific tape innovation opportunity?"
      - "How do consumers organize their tape collection?"

    search_terms:
      - "Scotch tape garage organization"
      - "ScotchBlue garage DIY"
      - "tape storage garage solutions"
      - "heavy duty tape garage mounting"

  - name: "Post-it"
    priority: 4
    garage_relevance: "MEDIUM"

    rationale: |
      Post-it Extreme Notes designed specifically for rough surfaces (wood, brick, cement, steel)
      with 100X holding power, water-resistant, works in hot/cold environments. Use cases:
      labeling pipes, dials, zone planning with color-coding.

      CHALLENGE: Painter's tape + marker more commonly used than Post-its for garage labeling.
      INSIGHT: Extreme line has garage credibility, regular Post-its don't.

    consumer_perception_themes:
      - "Post-it Extreme = rough surface capability"
      - "Labeling and zone planning applications"
      - "Competition from painter's tape + marker"
      - "Regular Post-its lack garage credibility"

    strategic_questions:
      - "Does consumer know Post-it Extreme exists?"
      - "Can Post-it own garage planning/labeling vs painter's tape?"
      - "What's the value proposition over cheaper alternatives?"

    search_terms:
      - "Post-it Extreme garage workshop"
      - "Post-it notes garage organization"
      - "garage labeling solutions"
      - "workshop organization planning"

  - name: "Scotchgard"
    priority: 5
    garage_relevance: "MEDIUM"

    rationale: |
      Technology exists for floor/surface protection (vinyl, concrete, stone) with positive
      reviews for automotive carpet protection. Relevant applications: garage floors,
      workbenches, stored items protection.

      GAP: Not top-of-mind for garage applications despite relevant technology.
      Consumers don't associate Scotchgard with garage, even though it could solve problems there.

    consumer_perception_themes:
      - "Fabric/carpet protection (primary association)"
      - "Automotive use (positive reviews)"
      - "Floor protection products exist but low awareness"
      - "Garage relevance: latent, not active"

    strategic_questions:
      - "Can Scotchgard shift perception from fabric-only to surface protection?"
      - "Would consumers think to use Scotchgard in garage context?"
      - "What garage-specific protection needs are unmet?"

    search_terms:
      - "Scotchgard garage floor protection"
      - "Scotchgard workbench surface protection"
      - "garage floor coating reviews"
      - "Scotchgard concrete sealer"

# Collection Configuration
collection:
  timeframe_months: 18

  sources:
    reddit:
      enabled: true
      subreddits:
        - "HomeImprovement"
        - "organization"
        - "DIY"
        - "homeowners"
        - "Garages"
        - "workbenches"

    youtube:
      enabled: true
      search_categories:
        - "home organization"
        - "garage makeover"
        - "DIY storage"
        - "workshop organization"

    amazon:
      enabled: true
      rating_filters: [1, 5]  # Both negative and positive reviews
      categories:
        - "Home Improvement"
        - "Storage & Organization"
        - "Garage & Shop"

    social:
      enabled: true
      platforms: ["tiktok", "instagram"]
      hashtags:
        - "#garageorganization"
        - "#homeorganization"
        - "#diystorage"
        - "#workshoporganization"

# AI Research Metadata
research_metadata:
  method: "AI-driven WebSearch + Claude reasoning"
  date_generated: "2025-10-30"
  sources_consulted:
    - "3M official brand portfolio (3m.com)"
    - "Command garage storage consumer discussions"
    - "Scotch-Brite workshop usage forums"
    - "Scotch tape DIY garage projects"
    - "Post-it Extreme product research"
    - "Scotchgard floor protection reviews"

  key_insights:
    - "Command has perception gap: loved for damage-free but seen as light-duty"
    - "Scotch-Brite has strong workshop authenticity, existing Garage Toolkit"
    - "Scotch is DIY enabler, not hero product in garage context"
    - "Post-it Extreme designed for rough surfaces, low consumer awareness"
    - "Scotchgard technology relevant to garage but not top-of-mind"

  northstar_compliance:
    no_fabrication: "All brand insights sourced from real web search results"
    verifiable: "Every claim traceable to WebSearch findings"
    ai_reasoning: "Brand selection via intelligence, not keyword counting"
    strategic: "Identified perception gaps and innovation opportunities"
