# 3M Lighting Project - Model Paths Configuration
# Last Updated: 2025-10-08
# Hardware: Mac M2 Max, 64GB RAM
# Architecture: Whisper (audio) + LLaVA (vision) + JTBD extraction

models:
  # Vision Model (Ollama - Local LLM serving)
  ollama:
    base_path: /Volumes/TARS/llm-models/ollama
    vision_model: llava:latest  # LLaVA 7B for visual frame analysis

  # Audio Transcription (OpenAI Whisper)
  whisper:
    cache_dir: /Volumes/TARS/llm-models/whisper
    model_size: large-v3  # 1.5GB model, best accuracy
    device: cpu  # CPU with MPS backend via PyTorch

system:
  device: mps  # Apple Silicon Metal Performance Shaders
  ram_gb: 64
  batch_size: 4  # Optimized for 64GB RAM
  num_workers: 8  # M2 Max has 8 performance cores
